apiVersion: v1
kind: Pod
metadata:
   name: mywebapp1
   labels:
      role: webserver-role
      app: nginx
spec:
   containers:
   - name: webserver1
     image: nginx
     ports: 
       - containerPort: 80
   - name: database-server
     image: mysql-3.4
     ports:
       - containerPort: 3306
